### ISSUE TITLE
NSFW checks

### ISSUE THREAD

**Issue by homeonarange** [youmslinky/report-bot#8]
make the bot check if the channel it's posting in is nsfw before posting nsfw content.

**Comment by youmslinky** [comment]
not really possible to do with the current discord.py

if we port to the rewrite, could be easily implemented

right now we could just whitelist the channels its allowed in.

**Comment by youmslinky** [comment]
dd012531d74b47c6b61c54537f2059c2f14147ab
aee84a8169db167c2da50930cbdde4018019b1c8
Added

**Comment by youmslinky** [comment]
4299cb05f51d2c09fbeb706e17c44da40a2bedf6
